### ISSUE TITLE
make it go backwards?

### ISSUE THREAD

**Issue by paultopia** [blakegarretson/smart-quotes-plus#10]
Would you entertain a PR to add functionality to convert the other way (smart quotes to dumb quotes etc.) along the lines of [this ST3 plugin](https://github.com/paultopia/ascii_punctuation)?  

(On the other hand, if you'd prefer to keep this plugin simple, would you be annoyed if I just forked it to make a new one that goes the other way?  Permissive open source licenses aside, that level of stealing seems potentially impolite :grinning: )

**Comment by DawnPaladin** [comment]
I'd love an extension that quickly fixes text pasted in from MS Word  :smile:

**Comment by benunderw** [comment]
I second this, and I found this plugin from searching for this exact functionality. Right now, my use case is fairly infrequent, so I'm getting by with using [this online tool](https://dan.hersam.com/tools/smart-quotes.html) when the need arises, though it's not as elegant of a solution.

**Comment by blakegarretson** [comment]
Alright Ben, update the package and give v3.0 a try.  It now handles "dumb" replacement in addition to the original smart replacement.  The key binding is SHIFT-ALT-' instead of the usual CTRL-ALT-'.
