### ISSUE TITLE
Doesn't catch straight quotes following commas

### ISSUE THREAD

**Issue by DSB1984** [blakegarretson/smart-quotes-plus#7]
Blake,

I've been using this package and it's a lifesaver. Thank you! I noticed, though, that it doesn't catch straight quotes following commas. For example, it won't catch the quote at the end of a phrase like "at the border,".

I'd fix it myself if I knew how.

**Comment by blakegarretson** [comment]
This is now fixed in v2.1.0.  I hadn't really thought of that use case.  Give it a whirl, and let me know of any problems.

**Comment by DSB1984** [comment]
Works great. Thanks for the update, Blake!

www.DavidBusis.com <http://www.davidbusis.com/>
